### ISSUE TITLE
Greater granularity when generating config files

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/clickward#6]
In order to be able to use clickward to generate production level configuration files we need to be able to set the following via the command line:

- [ ] Generate a single file of the cluster. This is necessary when deploying clickhouse server and keepers on different hosts. We may need to save more metadata to do this.
- [ ] Set target directory for saving generated files
- [ ] Replica and keeper listen host
- [ ] Hosts of the other replicas/keepers
- [ ] Display name
- [ ] Ports? (unsure about this one)

Related: https://github.com/oxidecomputer/omicron/issues/5999

**Comment by karencfv** [comment]
I was going to add a bunch of flags to be able to set the different hosts and other fields, but I realised it was going to become a flag madness fest. I'm thinking of passing a toml configuration file instead. Something like:

```
$ clickward gen-config --config some-file.toml
```

Where the configuration looks something like this:

```toml
[replica]
listen_host = 123.2.3.4
external_host = replica1.oxide.com

[replica]
listen_host = 123.2.3.5
external_host = replica2.oxide.com

[keeper]
listen_host = 123.2.3.6
external_host = keeper1.oxide.com

[keeper]
listen_host = 123.2.3.7
external_host = keeper2.oxide.com

[keeper]
listen_host = 123.2.3.8
external_host = keeper3.oxide.com
```

@andrewjstone what do you think?
